In [ ]:
#### PANDAS ---A POWERFUL data manipulation library in python used for data analysis and data cleaning.
## It has two data structure:series (like object) and dataframe(tabular data structure)

In [ ]:
import pandas as pd

In [2]:
### SERIES --- a one dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, python objects, etc.). A pandas Series is like a column in a table. It is a one-dimensional array holding data of any type.

In [6]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("series \n",series)
print(type(series))

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [7]:
### create series from dictionary
data = {'a':3,'b':2, 'c': 4, 'd':5}
series_dict = pd.Series(data)
print(series_dict)

a    3
b    2
c    4
d    5
dtype: int64

In [8]:
data = [10,20,30,67,34] 
index =['a','b','c','d','e']
pd.Series(data,index)

a    10
b    20
c    30
d    67
e    34
dtype: int64

In [16]:
### Data frames --- a table that is multidimension: having multiple rows and columns
### create a dataframe from a dictionary 
data = {
    'name':['john','jack','colin'],
    'age':[22,34,23],
    'city':['kenya','india','egpyt']
}
df=pd.DataFrame(data)
print(df)
print(type(data))
print (type(df))

    name  age   city
0   john   22  kenya
1   jack   34  india
2  colin   23  egpyt
<class 'dict'>
<class 'pandas.DataFrame'>

In [19]:
import numpy as np
np.array(df)

array([['john', 22, 'kenya'],
       ['jack', 34, 'india'],
       ['colin', 23, 'egpyt']], dtype=object)

In [23]:
#### create a datafram from a list of dictionary


data = [
    {'name':'jane','age':23,'city':"cairo"},
     {'name':'colin','age':33,'city':"london"},
     {'name':'khole','age':22,'city':"nigeria"} ,  
    {'name':'john', 'age':18, 'city':'chad'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    name  age     city
0   jane   23    cairo
1  colin   33   london
2  khole   22  nigeria
3   john   18     chad
<class 'pandas.DataFrame'>

In [24]:
#### ACCESSING data from dataframe
data

[{'name': 'jane', 'age': 23, 'city': 'cairo'},
 {'name': 'colin', 'age': 33, 'city': 'london'},
 {'name': 'khole', 'age': 22, 'city': 'nigeria'},
 {'name': 'john', 'age': 18, 'city': 'chad'}]

In [26]:
df

    name  age     city
0   jane   23    cairo
1  colin   33   london
2  khole   22  nigeria
3   john   18     chad

In [27]:
df['name']

0     jane
1    colin
2    khole
3     john
Name: name, dtype: str

In [28]:
df['city']

0      cairo
1     london
2    nigeria
3       chad
Name: city, dtype: str

In [31]:
type(df['name'])

pandas.Series

In [ ]:
#### this prints the data frame of the index 0,1,2,3 of the Data

df.loc[3]
df.loc[0]

name     jane
age        23
city    cairo
Name: 0, dtype: object

In [41]:
df.iloc[0],[3]

(name     jane
 age        23
 city    cairo
 Name: 0, dtype: object,
 [3])

In [45]:
### accessing specified elements
df

    name  age     city
0   jane   23    cairo
1  colin   33   london
2  khole   22  nigeria
3   john   18     chad

In [49]:
df.at[1,'age']

np.int64(33)

In [51]:
df.at[2,'city']

'nigeria'

In [53]:
df.at[3,'name']

'john'

In [56]:
### accessing specific elememt usind iat
df.iat[2,2]

'nigeria'

In [61]:
df.iat[1,2]

'london'

In [63]:
## Data manipulation with Dataframe
df

    name  age     city
0   jane   23    cairo
1  colin   33   london
2  khole   22  nigeria
3   john   18     chad

In [68]:
### adding a new coulnm
df['salary'] = [20000,35000,12000,30000]
df

    name  age     city  salary
0   jane   23    cairo   20000
1  colin   33   london   35000
2  khole   22  nigeria   12000
3   john   18     chad   30000

In [71]:
## remove column
df.drop('city',axis=1)

    name  age  salary
0   jane   23   20000
1  colin   33   35000
2  khole   22   12000
3   john   18   30000

In [72]:
df

    name  age     city  salary
0   jane   23    cairo   20000
1  colin   33   london   35000
2  khole   22  nigeria   12000
3   john   18     chad   30000

In [ ]:
df.drop('city',axis=1,inplace=True)

In [80]:
df

    name  age  salary
0   jane   23   20000
1  colin   33   35000
2  khole   22   12000
3   john   18   30000

In [ ]:
df['age'] = df ['age'] + 1
df

#### i accidently run it incorrectly

    name  age  salary
0   jane   21   20000
1  colin   21   35000
2  khole   21   12000
3   john   21   30000

In [91]:
df

    name  age  salary
0   jane   21   20000
1  colin   21   35000
2  khole   21   12000
3   john   21   30000

In [93]:
df.drop(0)

    name  age  salary
1  colin   21   35000
2  khole   21   12000
3   john   21   30000