### EDA and Feature Engineering Flight Price Prediction

In [2]:
### importing basic libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
df = pd.read_csv("flight.csv",)

df.head()

C:\Users\user\AppData\Local\Temp\ipykernel_11904\552520772.py:1: DtypeWarning: Columns (0: date) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("flight.csv",)

,Unnamed: 0,airline,date,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,11/2/2022,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,11/2/2022,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,11/2/2022,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,11/2/2022,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,11/2/2022,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [30]:
df.tail ()

,Unnamed: 0,airline,date,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300148,300148,Vistara,NaN,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,NaN,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,NaN,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,NaN,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,NaN,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  str
 2   date              206774 non-null  str
 3   flight            300153 non-null  str
 4   source_city       300153 non-null  str
 5   departure_time    300153 non-null  str
 6   stops             300153 non-null  str
 7   arrival_time      300153 non-null  str
 8   destination_city  300153 non-null  str
 9   class             300153 non-null  str
 10  duration          300153 non-null  float64
 11  days_left         300153 non-null  int64
 12  price             300153 non-null  int64
dtypes: float64(1), int64(3), str(9)
memory usage: 47.1 MB

In [32]:
df.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [33]:
df.head()

,Unnamed: 0,airline,date,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,11/2/2022,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,11/2/2022,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,11/2/2022,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,11/2/2022,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,11/2/2022,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [36]:
### Feature Engineering
df['date']

0         11/2/2022
1         11/2/2022
2         11/2/2022
3         11/2/2022
4         11/2/2022
            ...
300148          NaN
300149          NaN
300150          NaN
300151          NaN
300152          NaN
Name: date, Length: 300153, dtype: str

In [37]:
df['date']

0         11/2/2022
1         11/2/2022
2         11/2/2022
3         11/2/2022
4         11/2/2022
            ...
300148          NaN
300149          NaN
300150          NaN
300151          NaN
300152          NaN
Name: date, Length: 300153, dtype: str

In [49]:
df['Date'] = df['date'].str.split('/').str[0]
df['Month'] = df['date'].str.split('/').str[1]
df['Year'] = df['date'].str.split('/').str[2]

In [64]:
df.head()

,Unnamed: 0,airline,date,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Date,Month,Year
0,0,SpiceJet,11/2/2022,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,11,2,2022
1,1,SpiceJet,11/2/2022,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,11,2,2022
2,2,AirAsia,11/2/2022,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,11,2,2022
3,3,Vistara,11/2/2022,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,11,2,2022
4,4,Vistara,11/2/2022,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,11,2,2022

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  str
 2   date              206774 non-null  str
 3   flight            300153 non-null  str
 4   source_city       300153 non-null  str
 5   departure_time    300153 non-null  str
 6   stops             300153 non-null  str
 7   arrival_time      300153 non-null  str
 8   destination_city  300153 non-null  str
 9   class             300153 non-null  str
 10  duration          300153 non-null  float64
 11  days_left         300153 non-null  int64
 12  price             300153 non-null  int64
 13  Date              206774 non-null  object
 14  Month             58332 non-null   object
 15  Year              58332 non-null   object
dtypes: float64(1), int64(3), object(3), str(9)
memory usage: 54.0+ MB

In [60]:
df['date'].head()

0    11/2/2022
1    11/2/2022
2    11/2/2022
3    11/2/2022
4    11/2/2022
Name: date, dtype: str

In [63]:
df[['date', 'Date', 'Month', 'Year']].head()

        date Date Month  Year
0  11/2/2022   11     2  2022
1  11/2/2022   11     2  2022
2  11/2/2022   11     2  2022
3  11/2/2022   11     2  2022
4  11/2/2022   11     2  2022

In [74]:
df['stops'].unique()

<ArrowStringArray>
['zero', 'one', 'two_or_more']
Length: 3, dtype: str

In [ ]:
df['stops']

0    one
Name: stops, dtype: str

In [81]:
df['airline'].unique()

<ArrowStringArray>
['SpiceJet', 'AirAsia', 'Vistara', 'GO_FIRST', 'Indigo', 'Air_India']
Length: 6, dtype: str

In [82]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()

In [83]:
encoder.fit_transform(df[['airline','class','destination_city']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 900459 stored elements and shape (300153, 14)>

In [84]:
encoder.fit_transform(df[['airline','class','destination_city']]).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], shape=(300153, 14))