#### EDA and Feature Engineering with Google Play Dataset

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [5]:
df = pd.read_csv("google_play_store_dataset.csv")

df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [9]:
df.shape

(10841, 13)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 2.2 MB

In [15]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [16]:
### summary of the dataset
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [18]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [19]:
#### insights and observation--- the dataset has missing value

In [20]:
df.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

In [12]:
df['Content Rating'].unique

<bound method Series.unique of 0          Everyone
1          Everyone
2          Everyone
3              Teen
4          Everyone
            ...
10836      Everyone
10837      Everyone
10838      Everyone
10839    Mature 17+
10840      Everyone
Name: Content Rating, Length: 10841, dtype: str>

### DATA CLEANING

In [21]:
df['Reviews'].unique()

<ArrowStringArray>
[   '159',    '967',  '87510', '215644',    '167',    '178',  '36815',
  '13791',    '121',  '13880',
 ...
   '2036',  '56496', '376223',    '785',   '5775',    '885',  '88486',
    '603',   '1195', '398307']
Length: 6002, dtype: str

In [23]:
df['Reviews'].str.isnumeric().sum()

np.int64(10840)

In [15]:
df[-df['Reviews'].str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [16]:
df_copy=df.copy()

In [17]:
df_copy=df_copy.drop(df_copy.index[10472])

In [22]:
df_copy[-df_copy['Reviews'].str.isnumeric()]

### it has been executed---it won't show

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [23]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  str
 4   Size            10840 non-null  str
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 2.3 MB

In [28]:
df_copy['Size'].unique()

<ArrowStringArray>
[  '19M',   '14M',  '8.7M',   '25M',  '2.8M',  '5.6M',   '29M',   '33M',
  '3.1M',   '28M',
 ...
  '467k',  '157k',   '44k',  '676k',   '67k',  '552k',  '885k', '1020k',
  '582k',  '619k']
Length: 461, dtype: str

In [ ]:
df_copy['Size'].str.replace('M','000')

0                     19000
1                     14000
2                    8.7000
3                     25000
4                    2.8000
                ...
10836                 53000
10837                3.6000
10838                9.5000
10839    Varies with device
10840                 19000
Name: Size, Length: 10840, dtype: str

In [34]:
df_copy['Size']=df_copy['Size'].str.replace('M','000')

In [36]:
df_copy['Size']= df_copy['Size'].str.replace('k','')

In [ ]:
df_copy['Size']= df_copy['Size'].replace('Varies with device',np.nan)

### this has been replaced to NAN

In [40]:
df_copy['Size']

0         19000
1         14000
2        8.7000
3         25000
4        2.8000
          ...
10836     53000
10837    3.6000
10838    9.5000
10839       NaN
10840     19000
Name: Size, Length: 10840, dtype: str

In [52]:
df['Price'].unique

<bound method Series.unique of 0        0
1        0
2        0
3        0
4        0
        ..
10836    0
10837    0
10838    0
10839    0
10840    0
Name: Price, Length: 10841, dtype: str>

In [51]:
df['Installs'].unique

<bound method Series.unique of 0            10,000+
1           500,000+
2         5,000,000+
3        50,000,000+
4           100,000+
            ...
10836         5,000+
10837           100+
10838         1,000+
10839         1,000+
10840    10,000,000+
Name: Installs, Length: 10841, dtype: str>

In [54]:
charts_to_remove=['+',',','$']
cols_to_clean=['Installs','Price']
for items in charts_to_remove:
    for cols in cols_to_clean:
        df_copy[cols]=df_copy[cols].str.replace(items,'')

In [55]:
df_copy['Installs'].unique

<bound method Series.unique of 0           10000
1          500000
2         5000000
3        50000000
4          100000
           ...
10836        5000
10837         100
10838        1000
10839        1000
10840    10000000
Name: Installs, Length: 10840, dtype: str>

In [56]:
df_copy['Price'].unique

<bound method Series.unique of 0        0
1        0
2        0
3        0
4        0
        ..
10836    0
10837    0
10838    0
10839    0
10840    0
Name: Price, Length: 10840, dtype: str>

In [58]:
df_copy['Installs']=df_copy['Installs'].astype('int')

In [60]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  str
 4   Size            9145 non-null   str
 5   Installs        10840 non-null  int64
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 2.2 MB

In [62]:
df['Last Updated'].unique()

<ArrowStringArray>
[   'January 7, 2018',   'January 15, 2018',     'August 1, 2018',
       'June 8, 2018',      'June 20, 2018',     'March 26, 2017',
     'April 26, 2018',      'June 14, 2018', 'September 20, 2017',
       'July 3, 2018',
 ...
  'November 23, 2015',      'June 17, 2012',  'February 27, 2015',
  'December 18, 2013',   'February 6, 2012',  'November 25, 2014',
       'May 19, 2016',   'January 20, 2014',  'February 16, 2014',
     'March 23, 2014']
Length: 1378, dtype: str

In [63]:
pd.to_datetime(df_copy['Last Updated'])

0       2018-01-07
1       2018-01-15
2       2018-08-01
3       2018-06-08
4       2018-06-20
           ...
10836   2017-07-25
10837   2018-07-06
10838   2017-01-20
10839   2015-01-19
10840   2018-07-25
Name: Last Updated, Length: 10840, dtype: datetime64[us]

In [64]:
df_copy['Last Updated']=pd.to_datetime(df_copy['Last Updated'])

In [70]:
df.copy['Day']=df_copy['Last Updated'].dt.day
df.copy['Month']=df_copy['Last Updated'].dt.month
df.copy['Year']=df_copy['Last Updated'].dt.year

TypeError: 'method' object does not support item assignment